/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.uniminuto.avionbomba.view;

import edu.uniminuto.avionbomba.util.Utils;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Yoiner Montoya
 */
public class MainView extends javax.swing.JFrame {

    private static class BombaLine extends JComponent {

        private final List<int[]> points = new ArrayList<>();

        public List<int[]> getPoints() {
            return points;
        }

        @Override
        public void paintComponent(java.awt.Graphics g) {
            System.out.println("PAINT LINE: " + this.points.size());
            for (int index = 0; index < this.points.size() - 1; index++) {
                g.setColor(Color.YELLOW);
                g.drawLine(this.points.get(index)[0], this.points.get(index)[1], this.points.get(index + 1)[0], this.points.get(index + 1)[1]);
            }

        }
    }

    /**
     * Hilo para la simulación del lanzamiento de la bomba;
     */
    private Timer avionTimer = null;

    private static final int KM_ON_PANEL = 15;
    private static final int PANEL_WITDH = 500;
    private static final int WIDTH_AIRPLANE = 48;
    private static final List<Timer> BOMBAS_TIMER = new ArrayList<>();
    private static final List<javax.swing.JLabel> BOMBAS_LABEL = new ArrayList<>();
    private static final List<BombaLine> BOMBAS_LINE = new ArrayList<>();

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        pararAvionButton.setVisible(false);
        avionLabel.setVisible(false);
        lanzarBombaButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fumularioInicialJPanel = new javax.swing.JPanel();
        iniciarAvionButton = new javax.swing.JButton();
        velocidadInicialLabel = new javax.swing.JLabel();
        velocidadInicialInput = new javax.swing.JTextField();
        altitudInput = new javax.swing.JTextField();
        altitudLabel = new javax.swing.JLabel();
        pararAvionButton = new javax.swing.JButton();
        lanzarBombaButton = new javax.swing.JButton();
        mapaJPanel = new javax.swing.JPanel();
        avionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciarAvionButton.setText("Iniciar avión");
        iniciarAvionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarAvionButtonActionPerformed(evt);
            }
        });

        velocidadInicialLabel.setText("Velocidad inicial (km/h)");

        velocidadInicialInput.setText("900");

        altitudInput.setText("12");

        altitudLabel.setText("Altitud (km)");

        pararAvionButton.setText("Parar avión");
        pararAvionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararAvionButtonActionPerformed(evt);
            }
        });

        lanzarBombaButton.setText("Lanzar bomba");
        lanzarBombaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarBombaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fumularioInicialJPanelLayout = new javax.swing.GroupLayout(fumularioInicialJPanel);
        fumularioInicialJPanel.setLayout(fumularioInicialJPanelLayout);
        fumularioInicialJPanelLayout.setHorizontalGroup(
            fumularioInicialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fumularioInicialJPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(fumularioInicialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(velocidadInicialInput)
                    .addComponent(velocidadInicialLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fumularioInicialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altitudInput)
                    .addComponent(altitudLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(iniciarAvionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pararAvionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lanzarBombaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fumularioInicialJPanelLayout.setVerticalGroup(
            fumularioInicialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fumularioInicialJPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(fumularioInicialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altitudLabel)
                    .addGroup(fumularioInicialJPanelLayout.createSequentialGroup()
                        .addComponent(velocidadInicialLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(fumularioInicialJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(velocidadInicialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altitudInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniciarAvionButton)
                            .addComponent(pararAvionButton)
                            .addComponent(lanzarBombaButton))))
                .addGap(28, 28, 28))
        );

        mapaJPanel.setPreferredSize(new java.awt.Dimension(PANEL_WITDH, 200 + WIDTH_AIRPLANE));

        avionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/uniminuto/avionbomba/resources/airplane.png"))); // NOI18N
        avionLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        avionLabel.setOpaque(true);

        javax.swing.GroupLayout mapaJPanelLayout = new javax.swing.GroupLayout(mapaJPanel);
        mapaJPanel.setLayout(mapaJPanelLayout);
        mapaJPanelLayout.setHorizontalGroup(
            mapaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaJPanelLayout.createSequentialGroup()
                .addComponent(avionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mapaJPanelLayout.setVerticalGroup(
            mapaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaJPanelLayout.createSequentialGroup()
                .addComponent(avionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fumularioInicialJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fumularioInicialJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mapaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarAvionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarAvionButtonActionPerformed
        iniciarAvionButton.setEnabled(false);
        altitudInput.setEnabled(false);
        velocidadInicialInput.setEnabled(false);

        BOMBAS_TIMER.clear();

        if (this.avionTimer != null) {
            this.avionTimer.stop();
        }

        final double velocidadIncial = Double.parseDouble(velocidadInicialInput.getText());

        final double kmBySecond = velocidadIncial / 3600.0;
        final Double unitsBySecond = PANEL_WITDH / (KM_ON_PANEL / kmBySecond);

        avionLabel.setBounds(0, 0, 48, 48);
        avionLabel.setVisible(true);
        this.avionTimer = new Timer(1000, (event) -> {
            int posX = avionLabel.getBounds().x + unitsBySecond.intValue();
            avionLabel.setBounds(posX, 0, 48, 48);

            if (posX > PANEL_WITDH) {
                pararAvionButtonActionPerformed(null);
            }
        });

        this.avionTimer.start();

        lanzarBombaButton.setVisible(true);
        pararAvionButton.setVisible(true);
    }//GEN-LAST:event_iniciarAvionButtonActionPerformed

    private void pararAvionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararAvionButtonActionPerformed
        if (this.avionTimer != null) {
            this.avionTimer.stop();
        }

        iniciarAvionButton.setEnabled(true);
        altitudInput.setEnabled(true);
        velocidadInicialInput.setEnabled(true);
        pararAvionButton.setVisible(false);
        avionLabel.setVisible(false);
        lanzarBombaButton.setVisible(false);
        this.mapaJPanel.repaint();

        for (Timer timer : BOMBAS_TIMER) {
            timer.stop();
        }
        BOMBAS_TIMER.clear();

        for (JLabel jLabel : BOMBAS_LABEL) {
            this.mapaJPanel.remove(jLabel);
            this.mapaJPanel.repaint();
        }
        BOMBAS_LABEL.clear();

        for (BombaLine bombaLine : BOMBAS_LINE) {
            this.mapaJPanel.remove(bombaLine);
            this.mapaJPanel.repaint();
        }
        BOMBAS_LINE.clear();
    }//GEN-LAST:event_pararAvionButtonActionPerformed

    private void lanzarBombaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarBombaButtonActionPerformed
        int posicionAvion = avionLabel.getBounds().x;

        final JLabel bombaLabel = new JLabel();
        bombaLabel.setBounds(posicionAvion + (WIDTH_AIRPLANE / 2), (WIDTH_AIRPLANE / 2), 5, 5);
        bombaLabel.setVisible(true);
        bombaLabel.setOpaque(true);
        bombaLabel.setBackground(Color.RED);
        this.mapaJPanel.add(bombaLabel);
        this.mapaJPanel.setComponentZOrder(bombaLabel, 0);
        BOMBAS_LABEL.add(bombaLabel);

        final BombaLine bombaLine = new BombaLine();
        bombaLine.getPoints().add(new int[]{bombaLabel.getX(), bombaLabel.getY()});
        this.mapaJPanel.add(bombaLine);
        final double altitud = Double.parseDouble(altitudInput.getText());
        final double velocidadX = Double.parseDouble(velocidadInicialInput.getText());

        final double pxi = Utils.convertPxToKm(bombaLabel.getX(), PANEL_WITDH, KM_ON_PANEL);
        final double pyi = altitud;
        final double[] posicionActual = new double[]{pxi, pyi};

        System.out.println("INIT BOMB: " + pxi + ", " + pyi);

        final int indexBomba = BOMBAS_TIMER.size();
        final Timer bombaTimer = new Timer(1000, (event) -> {
            double[] posiciones = Utils.nextPosition(posicionActual[0], velocidadX, posicionActual[1], -300.0, 1.0);
            posicionActual[0] = posiciones[0];
            posicionActual[1] = posiciones[1];

            System.out.println("MOVE BOMB: " + posicionActual[0] + ", " + posicionActual[1]);

            int posY = (200 + (WIDTH_AIRPLANE / 2)) - Utils.convertKmToPx(posicionActual[1], 200, altitud);
            int posX = Utils.convertKmToPx(posicionActual[0], PANEL_WITDH, KM_ON_PANEL);

            bombaLabel.setBounds(posX, posY, 5, 5);
            bombaLine.getPoints().add(new int[]{posX, posY});
            bombaLine.repaint();

            if (posY > 200 + WIDTH_AIRPLANE) {
                BOMBAS_TIMER.get(indexBomba).stop();
                this.mapaJPanel.remove(BOMBAS_LABEL.get(indexBomba));
                this.mapaJPanel.repaint();
            }
        });

        bombaTimer.start();

        BOMBAS_TIMER.add(bombaTimer);
    }//GEN-LAST:event_lanzarBombaButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altitudInput;
    private javax.swing.JLabel altitudLabel;
    private javax.swing.JLabel avionLabel;
    private javax.swing.JPanel fumularioInicialJPanel;
    private javax.swing.JButton iniciarAvionButton;
    private javax.swing.JButton lanzarBombaButton;
    private javax.swing.JPanel mapaJPanel;
    private javax.swing.JButton pararAvionButton;
    private javax.swing.JTextField velocidadInicialInput;
    private javax.swing.JLabel velocidadInicialLabel;
    // End of variables declaration//GEN-END:variables
}
